homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: !secret unit_system
  # Pick yours from here: http://en.wikipedia.org/wiki/
  # List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  # customize: !include customize.yaml
  #  packages: !include_dir_named packages

  customize:
    sensor.openweather_cloud_coverage:
      friendly_name: "Cloud coverage"
    sensor.openweather_condition:
      friendly_name: "Weather condition"
    sensor.openweather_forecast:
      friendly_name: "Weather forecast"
    sensor.openweather_humidity:
      friendly_name: "Humidity"
    sensor.openweather_pressure:
      friendly_name: "Weather pressure"
    sensor.openweather_rain:
      friendly_name: "Rain"
    sensor.openweather_snow:
      friendly_name: "Snow"
    sensor.openweather_temperature:
      friendly_name: "Temperature"
    sensor.openweather_wind_speed:
      friendly_name: "Wind speed"
    sensor.openweather_wind_bearing:
      friendly_name: "Wind bearing"
      hidden: true
    sensor.openweather_weather_code:
      friendly_name: "Weather code"
      hidden: true


# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  api_password: !secret hass_pass
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 5
  trusted_networks: !secret trusted_networks

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
# Optional, allows Home Assistant developers to focus on popular components.
# include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - yeelight

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

logger:
  default: debug
  logs:
    homeassistant.components.mqtt: debug

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  #  - platform: metoffice
  #  api_key: !secret weather_API_KEY_metoffice
  #  monitored_conditions:
  #    - weather
  #    - temperature
  #    - feels_like_temperature
  #    - wind_speed
  #    - wind_direction
  #    - wind_gust
  #    - visibility
  #    - visibility_distance
  #    - uv
  #    - precipitation
  #    - humidity

  - platform: openweathermap
    api_key: !secret weather_API_KEY_openweathermap
    name: OpenWeather
    forecast: true
    monitored_conditions:
      - weather
      - temperature
      - wind_speed
      - wind_bearing
      - humidity
      - pressure
      - clouds
      - rain
      - snow
      - weather_code

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

#group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

duckdns:
  domain: uavhome
  access_token: !secret duckdns_token

# Core Components

#group: !include groups.yaml
#automation: !include automations.yaml
#script: !include scripts.yaml
#zone: !include zones.yaml
#sensor: !include sensors.yaml
#binary_sensor: !include binary_sensors.yaml
#device_tracker: !include device_tracker.yaml
#camera: !include camera.yaml
#light: !include lights.yaml
#scene: !include scenes.yaml
#weather: !include weather.yaml

# Additional Components

# MQTT #
mqtt:
  broker: localhost
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  keepalive: 60
#mqtt_eventstream:
#  publish_topic: master
#  subscribe_topic: slave/#
#mqtt_statestream:
#  base_topic: homeassistant
#  publish_attributes: true
#  publish_timestamps: true

# media_player: !include components/players.yaml
media_player:
  - platform: plex
    name: Plex
    entity_namespace: plex
    include_non_clients: true
    scan_interval: 5
    show_all_controls: true
    use_custom_entity_ids: false
    use_episode_art: true
    IP_ADDRESS: !secret PLEX_IP
    port: !secret PLEX_PORT
    token: !secret PLEX_TOKEN
    ssl: true
    verify: false
    entity_id: theater_plex

alexa:


group:
  OfficeRoom_lights:
    name: Office room lights
    entities:
      - light.office_light_1
      - light.office_light_2
      - light.office_light_3
      - light.office_light_4


  BedRoom_lights:
    name: Bedroom lights
    entities:

  ShahzoRoom_lights:
    name: Shahzo lights
    entities:
      - light.shahzo_light_1
      - light.shahzo_light_2      
      - light.shahzo_light_3
      - light.shahzo_light_4

  Entrance_lights:
    name: Entrance lights
    entities:
      - light.entrance_light_1
      - light.entrance_light_2

  LivingRoom_lights:
    name: Living room lights
    entities:
 
  OfficeRoom_plugs:
    name: Office room plus
    entities:

  BedRoom_plugs:
    name: Bedroom plugs
    entities:

  ShahzoRoom_plugs:
    name: Shahzo plugs
    entities:

  Entrance_plugs:
    name: Entrance plugs
    entities:

  LivingRoom_plugs:
    name: Living room power sockets
    entities:
      - switch.smart_socket_3
      - switch.living_room_power_strip_1

  OfficeRoom_cameras:
    name: Office room cameras
    entities:
  BedRoom_cameras:
    name: Bedroom cameras
    entities:
  ShahzoRoom_cameras:
    name: Shahzo cameras
    entities:

  Entrance_cameras:
    name: Entrance cameras
    entities:

  LivingRoom_camaras:
    name: Living room cameras
    entities:

  OfficeRoom_motions_humidity:
    name: Office room motion and humidity sensors
    entities:
  BedRoom_motion_humidity:
    name: Bedroom motion and humidity sensors
    entities:
  ShahzoRoom_motion_humidity:
    name: Shahzo motion and humidity sensors
    entities:
  Entrance_motion_humidity:
    name: Entrance motion and humidity sensors
    entities:
  LivingRoom_motion_humiditys:
    name: Living room motion and humidity sensors
    entities:
       
  Weather_view:
    name: Weather
    view: yes
    entities:
      - sensor.openweather_cloud_coverage
      - sensor.openweather_condition
      - sensor.openweather_forecast
      - sensor.openweather_humidity
      - sensor.openweather_pressure
      - sensor.openweather_rain
      - sensor.openweather_snow
      - sensor.openweather_temperature
      - sensor.openweather_wind_speed
      - sensor.openweather_wind_bearing
      - sensor.openweather_weather_code

  MyOffice_view:
    name: My Office
    view: yes
    entities:
      - light.office_light_1
      - light.office_light_2
      - light.office_light_3
      - light.office_light_4

  BedRoom_view:
    name: Bedroom
    view: yes
    entities:

  ShahzoRoom_view:
    name: Shahzo Room
    view: yes
    entities:
      - light.shahzo_light_1
      - light.shahzo_light_2
      - light.shahzo_light_3
      - light.shahzo_light_4

  Entrance_view:
    name: Entrance
    view: yes
    entities:
      - light.entrance_light_1
      - light.entrance_light_2

  LivingRoom_view:
    name: Living room
    view: yes
    entities:
      - switch.smart_socket_3
      - switch.living_room_power_strip_1

light:
  - platform: mqtt
    name: "Office Light 1"
    command_topic: "cmnd/OfficeLamp1/POWER"
    state_topic: "tele/OfficeLamp1/STATE"
    state_value_template: "{{value_json.POWER}}"
    availability_topic: "tele/OfficeLamp1/LWT"
    brightness_command_topic: "cmnd/OfficeLamp1/Dimmer"
    brightness_state_topic: "tele/OfficeLamp2/STATE"
    brightness_scale: 255
    on_command_type: "brightness"
    brightness_value_template: "{{value_json.Dimmer}}"
    color_temp_command_topic: "cmnd/OfficeLamp1/CT"
    color_temp_state_topic: "tele/OfficeLamp1/STATE"
    color_temp_value_template: "{{value_json.CT}}"
    rgb_command_topic: "cmnd/OfficeLamp1/Color2"
    rgb_state_topic: "tele/OfficeLamp1/STATE"
    rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
    effect_command_topic: "cmnd/OfficeLamp1/Scheme"
    effect_state_topic: "tele/OfficeLamp1/STATE"
    effect_value_template: "{{value_json.Scheme}}"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: false

  - platform: mqtt
    name: "Office Light 2"
    command_topic: "cmnd/OfficeLamp2/POWER"
    state_topic: "tele/OfficeLamp2/STATE"
    state_value_template: "{{value_json.POWER}}"
    availability_topic: "tele/OfficeLamp2/LWT"
    brightness_command_topic: "cmnd/OfficeLamp2/Dimmer"
    brightness_state_topic: "tele/OfficeLamp2/STATE"
    brightness_scale: 255
    on_command_type: "brightness"
    brightness_value_template: "{{value_json.Dimmer}}"
    color_temp_command_topic: "cmnd/OfficeLamp2/CT"
    color_temp_state_topic: "tele/OfficeLamp2/STATE"
    color_temp_value_template: "{{value_json.CT}}"
    rgb_command_topic: "cmnd/OfficeLamp2/Color2"
    rgb_state_topic: "tele/OfficeLamp2/STATE"
    rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
    effect_command_topic: "cmnd/OfficeLamp2/Scheme"
    effect_state_topic: "tele/OfficeLamp2/STATE"
    effect_value_template: "{{value_json.Scheme}}"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: false

  - platform: mqtt
    name: "Office Light 3"
    command_topic: "cmnd/OfficeLamp3/POWER"
    state_topic: "tele/OfficeLamp3/STATE"
    state_value_template: "{{value_json.POWER}}"
    availability_topic: "tele/OfficeLamp3/LWT"
    brightness_command_topic: "cmnd/OfficeLamp3/Dimmer"
    brightness_state_topic: "tele/OfficeLamp3/STATE"
    brightness_scale: 255
    on_command_type: "brightness"
    brightness_value_template: "{{value_json.Dimmer}}"
    color_temp_command_topic: "cmnd/OfficeLamp3/CT"
    color_temp_state_topic: "tele/OfficeLamp3/STATE"
    color_temp_value_template: "{{value_json.CT}}"
    rgb_command_topic: "cmnd/OfficeLamp3/Color2"
    rgb_state_topic: "tele/OfficeLamp3/STATE"
    rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
    effect_command_topic: "cmnd/OfficeLamp3/Scheme"
    effect_state_topic: "tele/OfficeLamp3/STATE"
    effect_value_template: "{{value_json.Scheme}}"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: false

  - platform: mqtt
    name: "Office Light 4"
    command_topic: "cmnd/OfficeLamp4/POWER"
    state_topic: "tele/OfficeLamp4/STATE"
    state_value_template: "{{value_json.POWER}}"
    availability_topic: "tele/OfficeLamp4/LWT"
    brightness_command_topic: "cmnd/OfficeLamp4/Dimmer"
    brightness_state_topic: "tele/OfficeLamp4/STATE"
    brightness_scale: 255
    on_command_type: "brightness"
    brightness_value_template: "{{value_json.Dimmer}}"
    color_temp_command_topic: "cmnd/OfficeLamp4/CT"
    color_temp_state_topic: "tele/OfficeLamp4/STATE"
    color_temp_value_template: "{{value_json.CT}}"
    rgb_command_topic: "cmnd/OfficeLamp4/Color2"
    rgb_state_topic: "tele/OfficeLamp4/STATE"
    rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
    effect_command_topic: "cmnd/OfficeLamp4/Scheme"
    effect_state_topic: "tele/OfficeLamp4/STATE"
    effect_value_template: "{{value_json.Scheme}}"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: false

  - platform: mqtt
    name: "Shahzo Light 1"
    command_topic: "cmnd/ShahzoLamp1/POWER"
    state_topic: "tele/ShahzoLamp1/STATE"
    state_value_template: "{{value_json.POWER}}"
    availability_topic: "tele/ShahzoLamp1/LWT"
    brightness_command_topic: "cmnd/ShahzoLamp1/Dimmer"
    brightness_state_topic: "tele/ShahzoLamp1/STATE"
    brightness_scale: 255
    on_command_type: "brightness"
    brightness_value_template: "{{value_json.Dimmer}}"
    color_temp_command_topic: "cmnd/ShahzoLamp1/CT"
    color_temp_state_topic: "tele/ShahzoLamp1/STATE"
    color_temp_value_template: "{{value_json.CT}}"
    rgb_command_topic: "cmnd/ShahzoLamp1/Color2"
    rgb_state_topic: "tele/ShahzoLamp1/STATE"
    rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
    effect_command_topic: "cmnd/ShahzoLamp1/Scheme"
    effect_state_topic: "tele/ShahzoLamp1/STATE"
    effect_value_template: "{{value_json.Scheme}}"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: false

  - platform: mqtt
    name: "Shahzo Light 2"
    command_topic: "cmnd/ShahzoLamp2/POWER"
    state_topic: "tele/ShahzoLamp2/STATE"
    state_value_template: "{{value_json.POWER}}"
    availability_topic: "tele/ShahzoLamp2/LWT"
    brightness_command_topic: "cmnd/ShahzoLamp2/Dimmer"
    brightness_state_topic: "tele/ShahzoLamp2/STATE"
    brightness_scale: 255
    on_command_type: "brightness"
    brightness_value_template: "{{value_json.Dimmer}}"
    color_temp_command_topic: "cmnd/ShahzoLamp2/CT"
    color_temp_state_topic: "tele/ShahzoLamp2/STATE"
    color_temp_value_template: "{{value_json.CT}}"
    rgb_command_topic: "cmnd/ShahzoLamp2/Color2"
    rgb_state_topic: "tele/ShahzoLamp2/STATE"
    rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
    effect_command_topic: "cmnd/ShahzoLamp2/Scheme"
    effect_state_topic: "tele/ShahzoLamp2/STATE"
    effect_value_template: "{{value_json.Scheme}}"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: false

  - platform: mqtt
    name: "Shahzo Light 3"
    command_topic: "cmnd/ShahzoLamp3/POWER"
    state_topic: "tele/ShahzoLamp3/STATE"
    state_value_template: "{{value_json.POWER}}"
    availability_topic: "tele/ShahzoLamp3/LWT"
    brightness_command_topic: "cmnd/ShahzoLamp3/Dimmer"
    brightness_state_topic: "tele/ShahzoLamp3/STATE"
    brightness_scale: 255
    on_command_type: "brightness"
    brightness_value_template: "{{value_json.Dimmer}}"
    color_temp_command_topic: "cmnd/ShahzoLamp3/CT"
    color_temp_state_topic: "tele/ShahzoLamp3/STATE"
    color_temp_value_template: "{{value_json.CT}}"
    rgb_command_topic: "cmnd/ShahzoLamp3/Color2"
    rgb_state_topic: "tele/ShahzoLamp3/STATE"
    rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
    effect_command_topic: "cmnd/ShahzoLamp3/Scheme"
    effect_state_topic: "tele/ShahzoLamp3/STATE"
    effect_value_template: "{{value_json.Scheme}}"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: false

  - platform: mqtt
    name: "Shahzo Light 4"
    command_topic: "cmnd/ShahzoLamp4/POWER"
    state_topic: "tele/ShahzoLamp4/STATE"
    state_value_template: "{{value_json.POWER}}"
    availability_topic: "tele/ShahzoLamp4/LWT"
    brightness_command_topic: "cmnd/ShahzoLamp4/Dimmer"
    brightness_state_topic: "tele/ShahzoLamp4/STATE"
    brightness_scale: 255
    on_command_type: "brightness"
    brightness_value_template: "{{value_json.Dimmer}}"
    color_temp_command_topic: "cmnd/ShahzoLamp4/CT"
    color_temp_state_topic: "tele/ShahzoLamp4/STATE"
    color_temp_value_template: "{{value_json.CT}}"
    rgb_command_topic: "cmnd/ShahzoLamp4/Color2"
    rgb_state_topic: "tele/ShahzoLamp1/STATE"
    rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
    effect_command_topic: "cmnd/ShahzoLamp4/Scheme"
    effect_state_topic: "tele/ShahzoLamp4/STATE"
    effect_value_template: "{{value_json.Scheme}}"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: false

  - platform: yeelight
    devices:
      192.168.5.171:
        name: Entrance light 1
#        transition: 1000
#        use_music_mode: true
#        save_on_change: true
      192.168.5.54:
        name: Entrance light 2
#        transition: 1000
#        use_music_mode: true
#        save_on_change: true


switch:
  - platform: mqtt
    name: "Smart Socket 3"
    state_topic: "tele/SmartSocket3/STATE"
    command_topic: "cmnd/SmartSocket3/POWER"
    value_template: "{{ value_json.POWER }}"
    availability_topic: "tele/SmartSocket3/LWT"
    qos: 2
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "online"
    payload_not_available: "offline"
    retain: false

  - platform: mqtt
    name: "Living Room Power Strip 1"
    state_topic: "tele/LivingRoomPowerStrip1/POWER1/STATE"
    command_topic: "cmnd/LivingRoomPowerStrip1/POWER1/POWER"
    value_template: "{{ value_json.POWER }}"
    availability_topic: "tele/LivingRoomPowerStrip1/LWT"
    qos: 2
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "online"
    payload_not_available: "offline"
    retain: false

#  - platform: mqtt
#    name: "Living room power strip 1"
#    state_topic: "tele/LivingRoomPlug1/POWER2/STATE"
#    command_topic: "cmnd/LivingRoomPlug1/POWER2/POWER"
#    availability_topic: "tele/LivingRoomPlug1/POWER1/LWT"
#    qos: 1
#    payload_on: "ON"
#    payload_off: "OFF"
#    payload_available: "online"
#    payload_not_available: "offline"
#    retain: true

#  - platform: mqtt
#    name: "Living room power strip 1"
#    state_topic: "tele/LivingRoomPlug1/POWER3/STATE"
#    command_topic: "cmnd/LivingRoomPlug1/POWER3/POWER"
#    availability_topic: "tele/LivingRoomPlug1/POWER1/LWT"
#    qos: 1
#    payload_on: "ON"
#    payload_off: "OFF"
#    payload_available: "online"
#    payload_not_available: "offline"
#    retain: true

#  - platform: mqtt
#    name: "Living room power strip 1"
#    state_topic: "tele/LivingRoomPlug1/POWER4/STATE"
#    command_topic: "cmnd/LivingRoomPlug1/POWER4/POWER"
#    availability_topic: "tele/LivingRoomPlug1/POWER1/LWT"
#    qos: 1
#    payload_on: "ON"
#    payload_off: "OFF"
#    payload_available: "online"
#    payload_not_available: "offline"
#    retain: true

#  - platform: mqtt
#    name: "Living room power strip 1"
#    state_topic: "tele/LivingRoomPlug1/POWER5/STATE"
#    command_topic: "cmnd/LivingRoomPlug1/POWER5/POWER"
#    availability_topic: "tele/LivingRoomPlug1/POWER1/LWT"
#    qos: 1
#    payload_on: "ON"
#    payload_off: "OFF"
#    payload_available: "online"
#    payload_not_available: "offline"
#    retain: true

